import numpy as np
import pytest

from ppg import util
from ppg.tac import Tac


@pytest.fixture
def rng():
    return np.random.default_rng(0)


@pytest.fixture
def synth_aif(rng):
    """A smooth bolus-shaped input function on a uniform 1 second grid."""

    t = np.arange(0, 300, 1.0)
    cnt = 100.0 * t * np.exp(-t / 20.0) + 5.0 * np.exp(-t / 120.0)
    cnt = cnt + rng.normal(0, 0.01, cnt.shape[0])
    return Tac(t, cnt, dc=True, h_life=1220.0)


@pytest.fixture
def flow_two_truth():
    """True K1/k2 used to generate synth_pet from synth_aif."""

    return np.array([0.5, 0.05])


@pytest.fixture
def synth_pet(synth_aif, flow_two_truth):
    """PET tac generated by convolving synth_aif with a known 1-tissue kernel.

    Exists so FlowTwo/OhtaTwo/OneComp/TwoComp tests have a target with a
    known, recoverable ground truth.
    """

    K1, k2 = flow_two_truth
    pet_cnt = util.exp_conv(synth_aif.time, synth_aif.cnt, coef=[K1], rate=[k2])
    return Tac(synth_aif.time, pet_cnt, dc=True, h_life=1220.0)
